### PR TITLE
Adding XenServer 6.x support

### PR DESCRIPTION
**Pull request by rdobson**
This pull requests add support for:
   * Installing with a ISO visible on an ISO SR (ISOName)
   * Exporting disks using the Transfer VM (present on all 6.x systems)

### CODE REVIEW

**Comment by kongslund** [comment]
@rdobson Any chance you could complete this merge?

**Comment by kongslund** [comment]
@rdobson I can make a PR of this branch if you'd like: https://github.com/kongslund/packer-builder-xenserver/tree/merge-6.x-support

I rebased 6.x-support onto it so your commits look newer than they really are.

**Comment by rdobson** [comment]
Hi @kongslund - sorry, thank for your PR, I had a branch that was under-going some testing internally.

**Comment by kongslund** [comment]
It's great that this was finally merged. Thanks!

**Pull request merged**
